version: "3.8"

services:
  user-service:
    image: kaanakdik/user-service:1.0
    ports:
      - "5000:5000"
    deploy:
      replicas: 1

  product-service:
    image: kaanakdik/product-service:1.0
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
