version: "3.8"

services:
  user-service:
    image: kaanakdik/user-service
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == kaanubuntuserver

  product-service:
    image: kaanakdik/product-service
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ubuntu
