version: "3.8"

services:
  users:
    image: kaanakdik/user-service:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == kaanubuntuserver

  products:
    image: kaanakdik/product-service:latest
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ubuntu
