version: "3.8"

services:
  user-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: user_service_db
    volumes:
      - user-db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    deploy:
      placement:
        constraints:
          - node.hostname == kaanubuntuserver

  user-service:
    image: kaanakdik/user-service:1.5
    ports:
      - "5000:5000"
    depends_on:
      - user-db
    environment:
      - DB_HOST=user-db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=user_service_db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == kaanubuntuserver
     
  product-service:
    image: kaanakdik/product-service:1.0
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ubuntu


volumes:
  user-db-data: