version: "3.8"

services:
  users:
    build: ./user-service
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == kaanubuntuserver

  products:
    build: ./product-service
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ubuntu
