version: "3.8"

services:
  user-service:
    image: kaanakdik/user-service:1.0
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
<<<<<<< HEAD
=======
      placement:
        constraints:
          - node.labels.type == linuxmanager
          - node.labels.type == linuxworker
>>>>>>> b846ed77b33a2e24c5514a41db3638f34f2e10d7

  product-service:
    image: kaanakdik/product-service:1.0
    ports:
      - "5001:5001"
    deploy:
      replicas: 2
      restart_policy:
<<<<<<< HEAD
        condition: on-failure
=======
        condition: on-failure
      placement:
        constraints:
          - node.labels.type == linuxmanager
          - node.labels.type == linuxworker
>>>>>>> b846ed77b33a2e24c5514a41db3638f34f2e10d7
