version: "3.8"

services:
  user-service:
    image: user-service:1.0
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  product-service:
    image: product-service:1.0
    ports:
      - "5001:5001"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
